services:
  postgres:
    image: cimg/postgres:16.10-postgis
    environment:
      POSTGRES_DB: taqaddum
      POSTGRES_USER: taqaddum
      POSTGRES_PASSWORD: taqaddum_local_only
    ports: ['5432:5432']
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U taqaddum -d taqaddum']
  minio:
    image: quay.io/minio/minio:RELEASE.2024-12-18T13-15-44Z
    command: server /data --console-address ':9001'
    environment:
      MINIO_ROOT_USER: minio_local
      MINIO_ROOT_PASSWORD: minio_local_password_only
    ports: ['9000:9000', '9001:9001']
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      DATABASE_URL: postgresql://taqaddum:taqaddum_local_only@postgres:5432/taqaddum
      NODE_ENV: local
      PGSSLMODE: "disable"
      APP_VERSION: 0.1.0
      PORT: 3000
    ports: ['3000:3000']
    depends_on:
      postgres: { condition: service_healthy }
      minio: { condition: service_started }
  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile
    environment:
      NODE_ENV: local
      APP_VERSION: 0.1.0
    depends_on:
      postgres: { condition: service_healthy }
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        VITE_API_BASE_URL: "https://zany-halibut-x55gvqwj95jrcvvj-3000.app.github.dev"
    environment:
      VITE_API_BASE_URL: https://zany-halibut-x55gvqwj95jrcvvj-3000.app.github.dev
    ports: ['5173:80']
    depends_on: [api]
